steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'my-app'
    args: ['install'] # npm install
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'my-app'
    args: ['run', 'build'] # If using a build step: npm run build
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'my-app'
    args: ['app', 'deploy', '--quiet'] # gcloud app deploy
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '900s'